language: cpp
sudo: false
script: make -j

matrix:
  include:
    - os: linux
      addons:
        apt:
          packages:
          - build-essential
          - mingw-w64
          - clang
      compiler:
      - clang
      - gcc
    - os: osx
      compiler:
      - clang
      - gcc
      before_install:
      - brew update
      install:
      - brew install llvm
      - brew install mingw-w64