language: cpp
sudo: false
script: make

matrix:
  include:
    - os: linux
      addons:
        apt:
          packages:
          - build-essential
          - mingw-w64
          - clang
      compiler:
      - clang
      - gcc
    - os: osx
      compiler:
      - clang
      - gcc
      before_install:
      - brew update
      install:
      - brew install llvm --with-clang --with-clang-extra-tools
      - brew install mingw-x64