language: cpp
sudo: false
script: make

matrix:
  include:
    - os: linux
      addons:
        apt:
          packages:
          - build-essential
          - mingw-w64
          - clang
      compiler:
      - clang
      - gcc
    - os: osx
      compiler:
      - clang
      - gcc