language: cpp
sudo: false

matrix:
  include:
    - os: linux
      addons:
        apt:
          packages:
          - build-essential
          - mingw-w64
          - clang
      compiler:
      - clang
      - gcc
      script: make
    - os: osx
      compiler:
      - clang
      - gcc
      script:
      - brew install mingw-x64
      - make